apiVersion: v1
kind: Service
metadata:
  name: '{{ include "backplane-api.fullname" .  }}'
  labels:
    app.kubernetes.io/name: '{{ include "backplane-api.name" .  }}'
    helm.sh/chart: '{{ include "backplane-api.chart" .  }}'
    app.kubernetes.io/instance: '{{ .Release.Name  }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service  }}'
spec:
  selector:
    # app.kubernetes.io/name: '{{ include "backplane-api.name" .  }}'
    # app.kubernetes.io/instance: '{{ .Release.Name  }}'
    app: backplane-api
  ports:
  - name: https-backplane  #  Important: helps Istio detect HTTPS
    port: 443              # Clients will connect to this (e.g. Gateway)
    targetPort: 8001       # Your app listens on 8001
    protocol: TCP
