replicaCount: 2
image:
  repository: ""
  tag: ""
istio:
  enabled: true
  ingressNamespace: "aks-istio-ingress"
  ingressPort: "8443"
credsKeyVault:
  name: ""
  secret: ""
statefulset:
  imageName: ""
  replicaCount: 2
  podManagementPolicy: "Parallel"
  updateStrategy: "RollingUpdate"
  persistentVolume:
    size: "1Gi"
    storageClassName: "default"
service:
  name: backplane-api
  type: ClusterIP
  port: 443
  targetPort: 8001
  tlsSecretName: backplane-api-tls
dev:
  generateSelfSignedTls: true
secrets:
  authSecretName: ocm
serviceAccount:
  name: "frontend"
ocm:
  containerImage: arohcpsvcdev.azurecr.io/ocm-container
  containerImageTag: latest
  apiUrl: https://api.stage.openshift.com
  workloadIdentityClientId: ""
  workloadIdentityTenantId: ""
pullBinding:
  registry: arohcpsvcdev.azurecr.io
  scope: repository:app-sre/backplane-api:pull
  workloadIdentityClientId: ""
  workloadIdentityTenantId: ""
